### ISSUE TITLE
Memory issue - system size limit?

### ISSUE THREAD

**Issue by jalemkul** [GrossfieldLab/loos#118] opened 2024-03-04 19:43 UTC
## Describe the bug
I have a very large and complex system of a little over 4 million particles. I am having issues reimaging the system in CHARMM (we often run into issues when using DCD files created in OpenMM) and I tried LOOS with the `merge-traj` command. It immediately aborts (core dump) with the following error:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  Requested size exceeds max
```

CHARMM is able to process this system, but does not reimage appropriately. I am running on a large-memory node on Expanse, so there is definitely adequate memory on the hardware itself. I suspect I'm overflowing an array somewhere in LOOS.

## To Reproduce
```
merge-traj --centering-selection 'segid="SEG1"' --fix-imaging 1 ../equil/bigsystem.drude.psf full_recenter_loos.dcd full.dcd
```
I am using dummy file names and selections, but this is otherwise the exact command. I am happy to share files privately if needed, but it is an immense system. The PSF is over 900 MB!

## Expected behavior
Reimaging instead of a core dump :)

## LOOS version and platform
LOOS version 4.1.0, installed via conda. The hardware is a large-memory node on SDSC Expanse (AMD EPYC 7742, 128 CPU cores, 2 TB RAM).

## Additional context
I have tortured every program so far with this system, so I figured I would break something here.

**Comment by agrossfield** [comment] 2024-03-04 19:48
Hi Justin,

I'm a little surprised because I don't think we have any sort of hard-wired limits, and unless your submission to the queue has a limit on memory (though you might want to check that) I agree you shouldn't be running out of memory. Can you email me separately with a dropbox or equivalent link so I can play with it? 

Cheers,

Alan

PS I saw you from a distance at BPS a few weeks ago and I spoke to a couple of your students, but I missed the chance to chat.

**Comment by jalemkul** [comment] 2024-03-04 19:51
Thanks, Alan - there should be enough memory on the node. I can run other analysis (like CHARMM, catdcd, etc.) without an issue. I'll email you a link to share some example files. Sorry we didn't get a chance to talk more at BPS - you always had a crowd and I ended up getting talking to a lot of folks in other places.

**Comment by agrossfield** [comment] 2024-03-04 21:03
Sure enough, I can reproduce your problem:

```
(loos) jordan 3% python
Python 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:51) [Clang 14.0.4 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import loos
>>> system = loos.createSystem("XXX.psf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/agrossfield/miniconda3/envs/loos/lib/python3.11/site-packages/loos/loos.py", line 4661, in createSystem
    return _pyloos.createSystem(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Requested size exceeds max
```

I just checked the code for reading psfs, and there are no limits built into it. It just reads the file a line at a time, creating atoms as it goes then going back to add the bonds. When I have a few minutes, I'll try instrumenting the code to see at what stage it's failing, but there's little doubt it's running out of memory.

I still think it's worth checking the slurm (or whatever queue SDSC uses) settings to ensure you're asking for enough memory. I've seen systems that deliberately have tiny defaults.

**Comment by lgsmith** [comment] 2024-03-04 21:59
Not to say something out of turn here, but running a ripgrep on the repo finds two instances of a std logic error that throws the message in the OP. Both occur in `src/util.cpp`, one in `parseStringAsHybrid36` and the other in `hybrid36AsString`. I found `parseStringAsHybrid36` being called in both `src/pdb.cpp` and `src/psf.cpp`. It looks like it's being used on 117 and 118 in the `read(std::istream&)` function, which seems like the likeliest source.

**Comment by agrossfield** [comment] 2024-03-04 22:30
Damnit, I hate when @lgsmith is right. More importantly, calling `parseStringAsHybrid36` is actually incorrect, since psf isn't a fixed-width format. I'll throw a fix up shortly, though you'll need to build from source until we get around to releasing a new conda package -- check in maybe half an hour.

**Comment by lgsmith** [comment] 2024-03-04 22:35
@agrossfield FWIW here's the ripgrep for that function's name:
```
./src/psf.cpp
117:        ind1 = parseStringAsHybrid36(buf1);
118:        ind2 = parseStringAsHybrid36(buf2);
166:    index = parseStringAsHybrid36(buf);
176:    resid = parseStringAsHybrid36(buf);

./src/pdb.cpp
78:    i = parseStringAsHybrid36(s, 6, 5);
93:    i = parseStringAsHybrid36(s, 22, 4);
264:    int bound_id = parseStringAsHybrid36(s, 6, 5);
279:      int id = parseStringAsHybrid36(t);

./src/utils.hpp
380:  int parseStringAsHybrid36(const std::string &source, const uint pos = 0, const uint nelem = 0);

./src/utils.cpp
259:  int parseStringAsHybrid36(const std::string &source, const uint pos, const uint nelem)

./src/catch_it.i
225:%catches(std::logic_error) parseStringAsHybrid36;
```
All the uses in `psf.cpp` may be suspect, given what you said. Maybe the ones in `pdb.cpp` are fine?

**Comment by agrossfield** [comment] 2024-03-04 22:35
I've verified I can read the psf you supplied on my mac with the fix I just pushed. Thank you @lgsmith for forcing me to look a second time.

@jalemkul : let me know once you've tried building and testing for yourself, so I can close this issue.

**Comment by agrossfield** [comment] 2024-03-04 22:37
@lgsmith : the uses in pdb are correct, because there it's a fixed-width format, and hybrid36 is one of the many non-standard ways of working around the limited field-width. In psf, it was just an error, because they just write the number out.

**Comment by lgsmith** [comment] 2024-03-05 02:10
Yeah makes sense, I just wanted to be thorough.

**Comment by agrossfield** [comment] 2024-03-05 13:08
@jalemkul : Because the thing you're trying to reimage is a big complex containing multiple molecules, it is possible that simple recentering *might* not be enough to fix it. I discuss some strategies for dealing with this problem in the wiki section on simulating membranes (which can have analogous problems):
https://github.com/GrossfieldLab/loos/wiki/Analyzing-membrane-simulations

To briefly summarize the strategy: you might want to pick an atom or residue that's near the center of your complex when it's correctly imaged and use that for your centering selection, while also using the `--postcenter` option selecting your entire complex. This centers and reimages the system using the first selection, then recenters it using the second one. The `--selection-is-split` option does something similar, but this way gives you better control of what is used for the initial centering, which can matter for big complexes that may span over half the box dimension.

**Comment by jalemkul** [comment] 2024-03-05 14:48
Thanks @agrossfield @lgsmith! The core issue is fixed with the patch that Alan pushed. I am able to successfully run the command. I will follow Alan's advice on the actual recentering (I assumed it would not be super simple but I'm happy to tinker with it).

**Comment by agrossfield** [comment] 2024-03-05 14:56
Sounds good. I'll close this issue, but feel free to drop me a line by email if you need more system-specific suggestions.

**Closed by agrossfield** 2024-03-05 14:56 UTC
