### ISSUE TITLE
AlignedVirtualTrajectory doesn't work the right way when operating with a reference.

### ISSUE THREAD

**Issue by lgsmith** [GrossfieldLab/loos#103] opened 2023-02-21 06:56 UTC
## Describe the bug
Aligned VTraj doesn't work when operating in a reference mode (I'm pretty sure the iterative alignment version of the code is fine).

## To Reproduce
Align some sample traj to a reference structure (preferably one it's similar to or that you already know what the RMSDs to that reference should be). Now loop over the trajectory and re=compute the same RMSDs using the method to AtomicGroup. The RMSDs will be as high as they were prior to being aligned in the vtraj.

If one calls superposition, then applies the xform oneself in a for-loop over a regular old vtraj the RMSDs are (as expected) low/normal numbers. see [additional context](#additional_context) but I think the call to superposition within the class's `_align` method might be applied backward.

## Expected behavior

- I was expecting the frames to have been aligned to the reference so that their coordinates were transformed. Aligned to reference implies that the trajectory's coords are transformed to align to the reference structure's coords, which don't change.
- I also was expecting (hoping?) that the RMSD to each frame after superposition might just get stored in the traj, so that I wouldn't have to write a second python for-loop to obtain them. I thought superposition could be made to return that...

## LOOS version and platform
Conda forge distribution, but based on looking at the source I think this is likely present in all modern LOOSes.

## Additional context
I believe the superposition call within AlignedVirtualTrajectory is being used backward, such that the transformations being applied to  the frames are actually transformations _for_ the reference, which is deep-copied and doesn't update when the trajectory is iterated over anyway. It's also a bit funny (possibly wrong) to think that the reference is what's being transformed, not the 'aligned' trajectory. I can imagine that odd notion coming back to bite us.

**Comment by agrossfield** [comment] 2023-02-23 19:45
Louis mentioned in conversation he thought the superpose call was backward, so that the reference got changed instead of the frame.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Feb 23, 2023, at 1:33 PM, Tod Romo ***@***.***> wrote:

﻿

Are you using the frames from the aligned vtraj? The aligned vtraj does not actually transform the contained trajectories. Rather, when you get a frame from it, it will apply aligned xform and return that.

Nothing is jumping out me from inspecting the code, but I can test it when I’m back in the office…

**Comment by tromo** [comment] 2023-02-23 21:18
No, it’s correct.  A.superposition(B) returns the transform to align A onto B.

**Comment by agrossfield** [comment] 2023-02-23 21:25
Louis, can you post and example?

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical Center

On Feb 23, 2023, at 4:19 PM, Tod Romo ***@***.***> wrote:

﻿

No, it’s correct. A.superposition(B) returns the transform to align A onto B.

**Comment by lgsmith** [comment] 2023-02-23 23:47
I'm getting a new frame using the `for _ in vtraj:` idiom, because I was relying on the avtraj working like a vtraj, where the identifying model and subset AGs get updated by the next operator. Pretty sure they don't, which is unexpected behavior and might encourage people to repeatedly run `selectAtoms` calls inside of the for-loop, defeating some of the value in having pAtoms.

Here's sample code that works (and avoids 'Aligned' virtual trajectory)
```
import loos
from loos import pyloos
from pathlib import Path
import numpy as np


ref_struct_p = Path('foo.pdb')
sel_string = Path('loos-sel-string.txt').read_text()
sample_conf_list = Path('samples_paths.txt').read_text().strip().split()
ref_struct = loos.createSystem(str(ref_struct_fn))

model = loos.createSystem(sample_conf_list[0])
samples_pocket = loos.selectAtoms(model, sel_string)
ref_pocket = loos.selectAtoms(ref_struct, sel_string)
vtraj = pyloos.VirtualTrajectory(
    *(pyloos.Trajectory(fn, model, subset=sel_string) for fn in sample_conf_list),
    reference=
)
rmsds = []
for _ in vtraj:
    xform = loos.XForm(samples_pocket.superposition(ref_pocket))
    samples_pocket.applyTransform(xform)
    rmsd = samples_pocket.rmsd(ref_pocket)
    rmsds.append(rmsd)

out = ref_struct_p.with_suffix('.npy')
np.save(str(out), rmsds)
```
Changing just the last part to use AlignedVirtualTrajectory gives something that runs, but produces incorrect RMSDs:
```
ref_struct = loos.createSystem('ref.pdb')
ref_pocket = loos.selectAtoms(ref_struct, sel_string
vtraj = pyloos.AlignedVirtualTrajectory(
    *(pyloos.Trajectory(fn, model, subset=sel_string) for fn in sample_conf_list),
    reference=ref_struct,
    alignwith=sel_string
)
rmsds = []
for _ in vtraj:
    rmsd = samples_pocket.rmsd(ref_pocket)
    rmsds.append(rmsd)

out = ref_struct_p.with_suffix('.npy')
np.save(str(out), rmsds)

```
Because of the way the other loos trajectory objects work, I would have also expected this to work. This is the only trajectory subclass where the iterator is actually producing a new AG that you are supposed to call things on subsequent to pulling it out of the iterator. What's more, it doesn't fail, or warn you that while it _is_ calling __next__ on the underlying trajs and therefore _is_ updating the subset group you set up to track, it _isn't_ applying the xform to it. It seems like a different contract with the user, at the very least.

I'm actually thinking that AlignedVirtualTrajectory's `__getitem__(self, i)` method is the source of the surprising behavior, because I would have expected the call to 'applyTransform' on line 770 to have updated the atomic group `model` from my example code, but it doesn't. The thing that's updating it is the call on 769 to `__getitem__` for the pyloos.Trajectory object--it's updating the coords, but not transforming them.

If you were thinking people might use this to co-align chemically distinct trajectories with an overlapping alignment selection, then I can see why it can't have a single 'model' atomic group that it updates, which then auto-updates all the subsets. Perhaps the real bug is that it _does_ work this way with the other python traj objects, and they need to be modified to save deepcopies of their model AGs, but that also seems kind of undesirable. 

From my perspective, if we'd like to offer both functionalities then we should make a different class and use a different word for it; for example, what about a `pyloos.Ensemble` and `pyloos.AlignedEnsemble` that work the way the VTrajs currently do (where you really should bind the output of the for statement to a variable and work on that within the loop) and change the VirtualTrajectory classes to work more like multitrajs that update the AGs associated with their definition whenever you call any relevant method on them, whatever such a method might be.

**Comment by tromo** [comment] 2023-02-24 02:03
I think this _should_ work, but you are in the quasi-pythonic territory of LOOS.  A lot of this was written before any of us had that good of a grasp on python and python idioms.  Really, I would love to rewrite all of this, but don’t have the time to do it.

AVT’s getitem() calls the VT’s getitem() which then goes into T’s getitem() which updates the model that was wrapped by that T.  Then, back in AVT, it gets transformed.  This _should_ be operating on the shared atoms from the original T, so it all should have worked.

I’m thinking that somewhere along the lines, the models got decoupled so it’s not updating what it thinks it’s updating.  One quick test you could try is to use the frame that the iteration returns (you’ll have to select atoms again) and see if that works.

I’ll have to look at this more closely when I’m back.

**Comment by tromo** [comment] 2023-02-24 16:02
Ok, bug confirmed.  If I get a chance, I’ll fix remotely, otherwise will fix when back.

Inside AVT’s align function, it never selects the subset to align against, so it’s actually passing two different AGs (correct subset from trajectory against the _entire_ reference structure) to the superposition function.  Nowhere in the C++ code do we validate the sizes of the groups match (oddly enough, RMSD does…).  So no exception was ever raised/thrown.

**Comment by agrossfield** [comment] 2023-02-24 16:07
Probably should add a check while you’re at it.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical School


On Feb 24, 2023, at 11:03 AM, Tod Romo ***@***.***> wrote:

﻿

Ok, bug confirmed. If I get a chance, I’ll fix remotely, otherwise will fix when back.

Inside AVT’s align function, it never selects the subset to align against, so it’s actually passing two different AGs (correct subset from trajectory against the entire reference structure) to the superposition function. Nowhere in the C++ code do we validate the sizes of the groups match (oddly enough, RMSD does…). So no exception was ever raised/thrown.

**Comment by lgsmith** [comment] 2023-02-24 19:14
I don't think this is true, but just to be sure: there's no utility in being able to superimpose onto a group of a larger size, right?  It's just going to match position i from data onto i from target, yes?

A feature I've wished loos had was something that mimics pymol's alignment function, which is robust to little differences in atom counts between structure and seems to largely figure out how to do the right thing because it has logic that selects a mutual subset (based on some part of the information within the input PDBs, I believe) to do the superposition with, before translating the whole object.

**Comment by agrossfield** [comment] 2023-02-24 19:22
No way to implement that without learning sone chemistry. Also, pymol’s is pretty brittle, iirc.

Dr. Alan Grossfield
Department of Biochemistry and Biophysics
University of Rochester Medical School


On Feb 24, 2023, at 2:15 PM, lgsmith ***@***.***> wrote:

﻿

I don't think this is true, but just to be sure: there's no utility in being able to superimpose onto a group of a larger size, right? It's just going to match position i from data onto i from target, yes?

A feature I've wished loos had was something that mimics pymol's alignment function, which is robust to little differences in atom counts between structure and seems to largely figure out how to do the right thing because it has logic that selects a mutual subset (based on some part of the information within the input PDBs, I believe) to do the superposition with, before translating the whole object.

**Comment by lgsmith** [comment] 2023-02-24 19:29
I think it actually does a primary sequence alignment. Pymol’d has been
able to deal with gaps and altlocs for the same chain from different
crystal structures, which is kind of the level of performance I’d hope for.

A selection map that could associate parts of an ag to parts of another ag
could be filled out by an alignment tool.

**Comment by tromo** [comment] 2023-02-27 01:36
FWIW, the bug is a logic error in the private align function and doesn’t matter if you subset or not.

**Comment by lgsmith** [comment] 2023-02-27 12:08
Oh that’s good to know. Yeah I actually use that feature a lot. I figured
it doesn’t matter much, but I also save files to dcd so they can be read
faster, and I do think saving a little memory makes it that much more
likely that the entire group stays in cache, but perhaps that doesn’t
usually matter.

Does this mean that other align calls are affected elsewhere or are you
talking about _align from AVT?

**Comment by tromo** [comment] 2023-03-27 14:51
This is fixed in the current main branch.

**Comment by tromo** [comment] 2023-03-27 15:00
I think it's fixed, but would feel more comfortable if it survived your use-case...  You can probably get by with updating the appropriate py file in-place.

**Comment by lgsmith** [comment] 2023-03-27 15:07
Ok I’ll test sometime today.

**Comment by ayanb73** [comment] 2023-04-03 16:58
For what it's worth, @tromo, I just pulled the version with your bug fix and tested it on one of my use cases, and it seems to work correctly. I used the same call to `AlignedVirtualTrajectory` as @lgsmith did -- with both `reference` and `alignwith` kwargs.

**Comment by agrossfield** [comment] 2023-04-03 17:18
That's great to hear. I'll check with @lgsmith one more time before closing.

**Closed** 2023-04-12 14:23 UTC
