### ISSUE TITLE
cmake doesn't detect BLAS libraries

### ISSUE THREAD

**Issue by blakemertz** [GrossfieldLab/loos#98] opened 2022-11-22 23:52 UTC
Alan and Tod,

I'm trying to roll my own installation in Debian 11. Have all of the pre-reqs installed as per the instructions. However, when I go to run cmake .., it's not detecting my BLAS libraries

`blake@blake-zephyrus-g14:/media/bak11/Linux/binaries/loos-4.0.3/build$ cmake ..
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of ulong
-- Check size of ulong - done
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: regex program_options 
-- Found NetCDF: /usr/include (found version "4.9.0") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.24/Modules/FindBLAS.cmake:1337 (find_package_handle_standard_args)
  CMakeLists.txt:42 (find_package)

-- Configuring incomplete, errors occurred!
See also "/media/bak11/Linux/binaries/loos-4.0.3/build/CMakeFiles/CMakeOutput.log".`

Only instance of BLAS I can find in the CMakeLists.txt file is:
`set(BLA_VENDOR OpenBLAS)
find_package(BLAS REQUIRED)
find_package(LAPACK REQUIRED)`

Is there some flag I need to pass onto cmake to explicitly define my BLAS location? Thanks.

**Comment by agrossfield** [comment] 2022-11-23 00:29
Is there a reason you don't want to do it with conda? That's *much* easier (eg `conda install -c conda-forge loos`).

LOOS is hardwired to want openblas these days -- we had issues with packaging on Mac when we just specified bias, because on the conda-forge machines they kept grabbing the blast from Xcode. Do you have openblas  and openblas-dev? I just looked at INSTALL.md, and I realize the hardwiring of openblas occurred AFTER I tested that install.

I'm looking at the debian11 package list, and I think the packages you'll want are libopenblas and libopenblas-dev.

**Comment by blakemertz** [comment] 2022-11-23 02:01
Alan,

Was just going with what has worked in the past for a system-based install on my laptop (and I'm anal retentive when it comes to bloat on my machine, so I try to avoid conda when I can -- impractical and old-fashioned, I know). Installing the openblas packages got me partway there, so will probably have to just bite the bullet and install conda. Below is the output after I went to compile (obviously need to install python virtualenv if I'm going to get all of the python-related goodies):

`blake@blake-zephyrus-g14:/media/bak11/Linux/binaries/loos-4.0.3/build$ sudo cmake --install .
-- Install configuration: ""
Processing ./src/pyloos
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: loos
  Building wheel for loos (pyproject.toml): started
  Building wheel for loos (pyproject.toml): finished with status 'done'
  Created wheel for loos: filename=loos-4.0.3-py3-none-any.whl size=1408313 sha256=262bea969cbab81c7bc3a8983bd894402da1c39816e1110483fe9045e5ed25d2
  Stored in directory: /tmp/pip-ephem-wheel-cache-gi8t6tlu/wheels/8f/40/1b/7c929a045a9b93a50f1833e7f7661ceca059e6827f7233e06d
Successfully built loos
Installing collected packages: loos
Successfully installed loos-4.0.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
-- Installing: /usr/local/src/loos-4.0.3/lib/_pyloos.so
-- Set runtime path of "/usr/local/src/loos-4.0.3/lib/_pyloos.so" to "/usr/local/src/loos-4.0.3/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial"
-- Installing: /usr/local/src/loos-4.0.3/lib/libloos.so
CMake Error at src/cmake_install.cmake:82 (file):
  file RPATH_CHANGE could not write new RPATH:

    /usr/local/src/loos-4.0.3/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial

  to the file:

    /usr/local/src/loos-4.0.3/lib/libloos.so

  The current RUNPATH is:

    /usr/lib/x86_64-linux-gnu/hdf5/serial:::::::::::::::

  which does not contain:

    /usr/lib/x86_64-linux-gnu/hdf5/serial::::::::::::::::::::::::::::::

  as was expected.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)

`

**Comment by agrossfield** [comment] 2022-11-23 02:39
The conda install of loos is actually not too big. If you build loos in a conda env, it's bigger because it pulls down the compilers), but you can have a pretty minimal conda env with just loos.

**Comment by agrossfield** [comment] 2022-11-23 02:40
Also, in the interests of me and @tromo trying to help you figure this out, can you send us your precise command lines and the output of the 3 cmake commands. I'll try to reproduce the problem in my vm when I get back in town.

**Comment by tromo** [comment] 2022-11-23 03:43
There were some changes to rpath handling necessitated by the MacOS conda-forge build, but I _thought_ those changes were isolated to Mac.

A general comment: I wouldn't be installing this as root.  While we don't do anything to intentionally increase risk for a system, there's no reason why it needs to be installed by root.  If you really want to install it in a system directory, then I'd do something like make the directory as root and chown it to a non-root user.

Another general comment: use miniconda rather than conda if you want to keep things as trim as possible.  Installing loos from conda-forge with miniconda will pull in just what it needs to run.

**Comment by lgsmith** [comment] 2022-11-23 05:21
So if you're trying to have a systemic install because it's a shared
machine and you want others to have access to the compilation, what do you
do? I kinda thought the way to do that was to install into opt, then give
people execute permissions on the binaries. If you chown it to a particular
user, do you still give everyone execute perms so they can put it on their
path?

**Comment by tromo** [comment] 2022-11-23 16:39
Exactly.  You can install into `/opt` as a non-root user.  You just have to create the destination ahead of time and make sure whatever user you are using can write there.  You may also want to check your `umask` before doing the install so that others can access (and deal with any facls, if using).

**Comment by blakemertz** [comment] 2022-11-29 14:43
Guys,

Thanks for the advice -- I was installing this on my old WVU laptop, so haven't had a chance to check in. I did do a miniconda install, Tod, trying to keep a minimal footprint as I only gave myself 40 GB for my root partition in linux and it's already getting cluttered.

Alan, will send you the three cmake commands when I get back on that laptop. And everyone thanks for the suggestion on non-root install into system directories -- great tip that I will use moving forward.

Blake

Adjunct Professor
C. Eugene Bennett Department of Chemistry
www.mertzlab-biophysics.com<http://www.mertzlab-biophysics.com>

Principal Scientist
Modulus Discovery

"Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves. We must believe that we are gifted for something and that this thing must be attained." Marie Curie

"Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible." St. Francis of Assisi
________________________________

**Comment by agrossfield** [comment] 2022-12-27 20:29
Hi Blake, 

Did you end us resolving this? Also, for what it's worth you don't need to install conda on the root partition -- install it somewhere in user-space.

**Comment by blakemertz** [comment] 2022-12-29 15:04
@agrossfield,

I was able to get loos installed in a miniconda environment. Below is a summary of the output of my three cmake commands (I can get you a full log of the cmake build command if need be):

cmake .. : (don't have this output, my terminal doesn't save that many lines)

cmake build . -j8:
`/media/Data/binaries/github/loos/src/Atom.hpp:285:35: warning: ‘template<class _Arg1, class _Arg2, class _Result> struct std::binary_function’ is deprecated [-Wdeprecated-declarations]
  285 |   struct AtomEquals : public std::binary_function<pAtom, pAtom, bool> {
      |                                   ^~~~~~~~~~~~~~~
In file included from /usr/include/c++/12/string:48,
                 from /usr/include/c++/12/bits/locale_classes.h:40,
                 from /usr/include/c++/12/bits/ios_base.h:41,
                 from /usr/include/c++/12/ios:42,
                 from /usr/include/c++/12/ostream:38,
                 from /usr/include/c++/12/iostream:39,
                 from /media/Data/binaries/github/loos/src/loos.hpp:33:
/usr/include/c++/12/bits/stl_function.h:131:12: note: declared here
  131 |     struct binary_function
      |            ^~~~~~~~~~~~~~~
/media/Data/binaries/github/loos/src/Atom.hpp:294:41: warning: ‘template<class _Arg1, class _Arg2, class _Result> struct std::binary_function’ is deprecated [-Wdeprecated-declarations]
  294 |   struct AtomCoordsEquals : public std::binary_function<pAtom, pAtom, bool> {
      |                                         ^~~~~~~~~~~~~~~
/usr/include/c++/12/bits/stl_function.h:131:12: note: declared here
  131 |     struct binary_function
      |            ^~~~~~~~~~~~~~~
[ 99%] Linking CXX executable gridavg
[ 99%] Built target gridavg
[100%] Linking CXX executable water-autocorrel
[100%] Built target water-autocorrel
[100%] Linking CXX executable water-survival
[100%] Built target water-survival
`

cmake -DCMAKE_INSTALL_RPEFIX=/usr/local/src/loos (I created a user-owned loos directory in /usr/local/src):
`-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: regex program_options 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: thread filesystem 
-- Documentation can be built using --target=docs
-- Configuring done
-- Generating done
-- Build files have been written to: /media/Data/binaries/github/loos/build
`

cmake --install . (cmake --install . -j8 wouldn't execute for some reason):
`-- Install configuration: ""
Processing ./src/pyloos
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: loos
  Building wheel for loos (pyproject.toml): started
  Building wheel for loos (pyproject.toml): finished with status 'done'
  Created wheel for loos: filename=loos-4.0.3-py3-none-any.whl size=1409081 sha256=21cbdec6410271c1bb4666496a2c2230c66cd46a942005f92434bb2655912e9c
  Stored in directory: /tmp/pip-ephem-wheel-cache-aqc2kp2k/wheels/f9/c3/84/f72ceb769a7def9370b6589c8d663afdf8e593452b65891745
Successfully built loos
Installing collected packages: loos
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/bin/OptimalMembraneGenerator'
Consider using the `--user` option or check the permissions.

-- Installing: /usr/local/src/loos/lib/_pyloos.so
-- Set runtime path of "/usr/local/src/loos/lib/_pyloos.so" to "/usr/local/src/loos/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial"
-- Installing: /usr/local/src/loos/lib/libloos.so
CMake Error at src/cmake_install.cmake:82 (file):
  file RPATH_CHANGE could not write new RPATH:

    /usr/local/src/loos/lib:/usr/lib/x86_64-linux-gnu/hdf5/serial

  to the file:

    /usr/local/src/loos/lib/libloos.so

  The current RUNPATH is:

    /usr/lib/x86_64-linux-gnu/hdf5/serial:::::::::::::::

  which does not contain:

    /usr/lib/x86_64-linux-gnu/hdf5/serial::::::::::::::::::::::::

  as was expected.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
`

**Comment by agrossfield** [comment] 2023-02-27 16:51
It looks like you were having permissions issues for the install. Did you a) use sudo for the install or b) set the permissions in /usr/local/src/loos/ to be user writeable? Did you check if there's some horrible selinux thing happening?

**Closed** 2023-12-28 21:02 UTC
